const pages = [
  "Zaczynamy",
  "O tobie",
  "Ocena powietrza",
  "Energetyka i Ogrzewanie",
  "Transport",
  "Kończymy",
];

const questions = [
  {
    id: 1,
    type: "singlechoice",
    length: "short",
    question: "Z jaką płcią się identyfikujesz?",
    answers: ["Kobieta", "Mężczyzna", "Inna"],
    default: true,
    page: pages[1],
  },
  {
    id: 2,
    type: "singlechoice",
    length: "short",
    question: "W jakim jesteś wieku?",
    answers: [
      "poniżej 18 lat",
      "18 - 25 lat",
      "26 - 35 lat",
      "36 - 45 lat",
      "46 - 65 lat",
      "powyżej 65 lat",
    ],
    default: true,
    page: pages[1],
  },
  {
    id: 3,
    type: "singlechoice",
    length: "short",
    question: "Gdzie mieszkasz?",
    answers: [
      "w mieszkaniu (blok/kamienica)",
      "w domu (jednorodzinnym/szeregowiec)",
    ],
    default: true,
    page: pages[1],
  },
  {
    id: 4,
    type: "singlechoice",
    length: "long",
    question: "Gdzie mieszkasz?",
    answers: [
      "w centrum Łodzi",
      "w Łodzi, poza centrum",
      "w okolicach Łodzi (Konstantynów Łódzki, Zgierz, etc)",
      "daleko od Łodzi, ale często tu bywam",
    ],
    default: true,
    page: pages[1],
  },
  {
    id: 5,
    type: "singlechoice",
    length: "short",
    question: "Jakie jest twoje wykształcenie?",
    answers: [
      "podstawowe / gimnazjalne / zawodowe",
      "średnie / średnie branżowe",
      "wyższe",
    ],
    default: true,
    page: pages[1],
  },
  {
    id: 6,
    type: "singlechoice",
    length: "short",
    question:
      "Jak istotna jest dla Ciebie jakość powietrza, którym oddychasz? (1 - wcale, 5 - bardzo)",
    answers: ["1", "2", "3", "4", "5"],
    default: true,
    page: pages[2],
  },
  {
    id: 7,
    type: "singlechoice",
    length: "short",
    question:
      "Jak oceniasz jakość powietrza w Łodzi w skali całego roku? (1 - bardzo zła, 5 - bardzo dobra)",
    answers: ["1", "2", "3", "4", "5"],
    default: true,
    page: pages[2],
  },
  {
    id: 8,
    type: "singlechoice",
    length: "short",
    question:
      "Jak oceniasz obecną jakość powietrza w porównaniu do tej sprzed 5 lat?",
    answers: [
      "Jest znacznie lepiej",
      "Jest nieco lepiej",
      "Bez zmian",
      "Jest nieco gorzej",
      "Jest znacznie gorzej",
    ],
    default: true,
    page: pages[2],
  },
  {
    id: 9,
    type: "singlechoice",
    length: "long",
    question: "Czy zanieczyszczenie powietrza miało wpływ na Twoje zdrowie?",
    answers: [
      "Tak - mam stwierdzone schorzenia których występowanie zwiększa smog",
      "Chyba tak - nie mam diagnozy, ale dostrzegam wpływ smogu na mnie",
      "Chyba nie - ale kto wie, co będzie za kilka lat",
      "Nie - i nie spodziewam się, żeby miało w przyszłości",
    ],
    default: true,
    page: pages[2],
  },
  {
    id: 10,
    type: "multichoice",
    length: "long",
    question:
      "Z jakich sposobów ogrzewania swojego domu / mieszkania korzystasz?",
    answers: [
      "Centralne ogrzewanie",
      "Prąd elektryczny",
      "Kocioł na gaz",
      "Piec węglowy",
      "Kominek",
      "Nie jestem pewien",
      "Inne",
    ],
    default: true,
    page: pages[3],
  },
  {
    id: 11,
    type: "singlechoice",
    length: "short",
    question:
      "Czy centralne ogrzewanie jest dostępne jako możliwość tam, gdzie mieszkasz?",
    answers: ["Tak", "Nie"],
    default: true,
    page: pages[3],
  },
  {
    id: 12,
    type: "singlechoice",
    length: "short",
    question:
      "Czy Twoje mieszkanie / dom było wcześniej ogrzewane piecem węglowym?",
    answers: ["Tak", "Nie"],
    default: true,
    page: pages[3],
  },
  {
    id: 13,
    type: "singlechoice",
    length: "short",
    question:
      "Czy słyszałeś o dofinansowaniach do wymiany starych pieców węglowych?",
    answers: ["Tak", "Nie"],
    default: true,
    page: pages[3],
  },
  {
    id: 14,
    type: "singlechoice",
    length: "short",
    question:
      "Czy wiesz ile kosztuje wymiana pieca węglowego lub jaka część kosztów jest refundowana w ramach programu?",
    answers: ["Tak", "Nie"],
    default: true,
    page: pages[3],
  },
  {
    id: 16,
    type: "singlechoice",
    length: "short",
    question: "Czy masz zainstalowane panele fotowoltaiczne?",
    answers: ["Tak", "Nie"],
    default: true,
    page: pages[3],
  },
  {
    id: 17,
    type: "singlechoice",
    length: "short",
    question: "Czy masz możliwość zainstalowania paneli fotowoltaicznych?",
    answers: ["Tak", "Nie"],
    default: true,
    page: pages[3],
  },
  {
    id: 18,
    type: "multipoint",
    question: "Z jakich środów transportu korzystasz?",
    answers: [
      "Samochód jako kierowca",
      "Samochód jako pasażer",
      "Komunikacja miejsca",
      "Taksówki / uber",
      "Skuter / motor",
      "Rower",
      "Hulajnogi elektryczne",
    ],
    options: ["Często", "Czasem", "Wcale"],
    default: true,
  },
  {
    id: 19,
    type: "singlechoice",
    length: "short",
    question: "Gdy kierujesz autem, ilu pasażerów zwykle zabierasz?",
    answers: ["0", "1", "2", "3", "4+"],
    default: true,
    page: pages[4],
  },
  {
    id: 20,
    type: "multichoice",
    howManyAnswers: 2,
    length: "long",
    question: "Dlaczego korzystasz z komunikacji miejskiej? (max 2)",
    answers: [
      "Nie mam samochodu",
      "Nie mam gdzie parkować samochodu",
      "Tak jest najtaniej",
      "Tak jest ekologiczniej",
      "Tak jest mi wygodnie",
      "Inne",
    ],
    default: true,
    page: pages[4],
  },
  {
    id: 21,
    type: "multichoice",
    howManyAnswers: 2,
    length: "long",
    question: "Dlaczego nie korzystasz z komunikacji miejskiej (max 2)",
    answers: [
      "Tak jest najszybciej",
      "Tak jest najwygodniej",
      "Przewożę dużo rzeczy",
      "Przewożę dużo osób",
      "Inne",
    ],
    default: true,
    page: pages[4],
  },
  {
    id: 22,
    type: "multichoice",
    howManyAnswers: 3,
    length: "long",
    question:
      "Jak poprawić MPK / Co by cię przekonało do korzystania z MPK? (max 3)",
    answers: [
      "krótszy czas podróży",
      "krótszy czas czekania na autobus",
      "mniejszy dystans do / z przystanków",
      "większa punktualność",
      "mniej przesiadek",
      "inne",
      "nie dam się przekonać",
    ],
    default: true,
    page: pages[4],
  },
  {
    id: 23,
    type: "singlechoice",
    howManyAnswers: 3,
    length: "long",
    question: "Ile jesteś gotów dopłacić za poprawę powyższych sfer?",
    answers: [
      "jeśli podwyższą ceny biletów, rezygnuję z MPK",
      "poniżej +50% ceny biletu",
      "+50% ceny biletu",
      "+100% ceny biletu",
      "+200% ceny biletu",
      "powyżej +200% ceny biletu",
    ],
    default: true,
    page: pages[4],
  },
  {
    id: 24,
    type: "multipoint",
    length: "long",
    question: "Jakie jest twoje nastawienie do poniższych rozwiązań?",
    answers: [
      "zwiększeniu liczby buspasów (również kosztem pasów dla kierowców)",
      "ograniczaniu wjazdu samochodów do centrum",
      "ulgom dla pojazdów elektrycznych (darmowe parkingi w centrum, możliwość korzystania z buspasów)?",
      "zwiększeniu cen biletów parkingowych",
    ],
    options: ["Jestem za", "Jakoś przeżyję", "Jestem przeciw"],
    default: true,
    page: pages[4],
  },
];

export { questions, pages };
